spring: 
  profiles: 
    active: 
    - dev

--- 

server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: servicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.167:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数  
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数    
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: fun.huanghai.springcloud.entity # 所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://192.168.1.167:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   
  instance:
    instance-id: servicecloud-config-dept-client8001
    prefer-ip-address: true  #访问路径可以显示IP地址
  info:     #info信息监控查看
    app.name: huanghai-servicecloud
    company.name: www.huanghai.fun
    build.artifactId: $project.artifactId$
    build.version: $project.version$
--- 
server: 
  port: 8001
spring: 
  profiles: test
  application: 
    name: servicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.167:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数  
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数    
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: fun.huanghai.springcloud.entity # 所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://192.168.1.167:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   
  instance:
    instance-id: servicecloud-config-dept-client8001
    prefer-ip-address: true  #访问路径可以显示IP地址
  info:     #info信息监控查看
    app.name: huanghai-servicecloud
    company.name: www.huanghai.fun
    build.artifactId: $project.artifactId$
    build.version: $project.version$
